[build]
  command = "pip install -r requirements.txt"
  publish = "public"

[functions]
  directory = "functions"
  included_files = ["templates/**", "static/**", "database/**", "modules/**", "app.py"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
